baseURL = 'http://skysora.github.io'
languageCode = 'en-us'
title = "Sora's Blog"

theme="hugo-theme-stack"

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"



[params.sidebar]
    subtitle = "what doesn't kill you makes you stronger"

[params.widgets.homepage]
    [params.widgets.homepage.search]
        title = "搜尋"
        placeholder="搜尋文章關鍵字"
        type = "search"
        weight = 5

    [params.widgets.homepage.archives]
        type = "archives"
        title = "歸檔"
        [params.widgets.homepage.archives.params]
            limit = 5
        weight = 4

    [params.widgets.homepage.categories]
        type = "categories"
        [params.widgets.homepage.categories.params]
            limit = 10
        weight = 3

    [params.widgets.homepage.tag-cloud]
        type = "tag-cloud"
        [params.widgets.homepage.tag-cloud.params]
            limit = 10
        weight = 2